// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2i7elAS_lOj7XeTc7g4EcjWtuCsENZo4',
    appId: '1:362194269972:web:7e7beaeaf2a5510c727401',
    messagingSenderId: '362194269972',
    projectId: 'chat-app-23368',
    authDomain: 'chat-app-23368.firebaseapp.com',
    storageBucket: 'chat-app-23368.firebasestorage.app',
    measurementId: 'G-HV0KNE62NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEjFYE5sGpUp3jQnqumXXSpqeDOGbe3o',
    appId: '1:362194269972:android:3d51ba21c0d56cdc727401',
    messagingSenderId: '362194269972',
    projectId: 'chat-app-23368',
    storageBucket: 'chat-app-23368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKL_u_ilI9iJdYy54Y2bJOeZBHCgV1Ug',
    appId: '1:362194269972:ios:10aa86ff332d24b2727401',
    messagingSenderId: '362194269972',
    projectId: 'chat-app-23368',
    storageBucket: 'chat-app-23368.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIKL_u_ilI9iJdYy54Y2bJOeZBHCgV1Ug',
    appId: '1:362194269972:ios:10aa86ff332d24b2727401',
    messagingSenderId: '362194269972',
    projectId: 'chat-app-23368',
    storageBucket: 'chat-app-23368.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2i7elAS_lOj7XeTc7g4EcjWtuCsENZo4',
    appId: '1:362194269972:web:537eda4462899458727401',
    messagingSenderId: '362194269972',
    projectId: 'chat-app-23368',
    authDomain: 'chat-app-23368.firebaseapp.com',
    storageBucket: 'chat-app-23368.firebasestorage.app',
    measurementId: 'G-BVNE9DPD7G',
  );
}
